version: '3.8'

services:
  web:
    build: ./backend/core
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/core/:/usr/src/backend/core/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=e-commerce
      - POSTGRES_PASSWORD=e-commerce
      - POSTGRES_DB=e-commerce-dev

volumes:
  postgres_data:
